[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "v6_logistic_regression_py"
version = "1.0.0"
description = "Vantage6 algorithm for logistic regression"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
keywords = ["Vantage6", "Federated Algorithms", "Supervised Learning"]
dependencies = [
    "vantage6-client",
    "v6-federated-algo-core-py @ git+ssh://git@github.com/mdw-nl/v6-federated-algo-core-v6.git",
    "pydantic>=2,<3",
    "vantage6-algorithm-tools>=4.13.1",
    "pandas>=1.2.1",
    "scipy>=1.7.3",
    "scikit-learn>=1.0.2",
    "flwr>=1.20.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4",
    "pytest-mock>=3.10",
]

[project.urls]
Homepage = "https://github.com/MaastrichtU-CDS/v6-logistic-regression-py"

[tool.setuptools.packages.find]
include = ["v6_logistic_regression_py*"]
